In Python, usually, the functions are included in libraries which sould be imported.
For example to import the scikit-learn library : 

In [12]:
from sklearn import *

Import the libraries numpy (scientific compûtation) and
matplotlib.pyplot (visualization).

In [13]:
import numpy as np
import matplotlib.pyplot as mp

Load the Iris dataset using:

In [14]:
iris = datasets.load_iris()

The variable iris is an object which contains the dataset matrix iris.data), a vector
containing the lable/classes (target), the name of variables (feature_names) and the
name of classes (target_names).

4- Print the number of data, names of variables and the name of classes (use print).


In [15]:
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [16]:
print('The names of the dataset variables:\n',iris['feature_names'])

The names of the dataset variables:
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [17]:
print(list(iris.target_names))

['setosa', 'versicolor', 'virginica']


B. Data normalization
The	 sklearn.preprocessing	 package	 provides	 several	 common	 utility	 functions	
and	transformer	classes	to	change	raw	feature	vectors	into	a	representation	that	
is	more	suitable	for	the	downstream	estimators.
Standardization of	 datasets	 is	 a	 common	 requirement	 for	 many	 machine	
learning	 estimators implemented	 in	 the	 scikit:	 they	 might	 behave	 badly	 if	 the	
individual	 feature	 do	 not	 more	 or	 less	 look	 like	 standard	 normally	 distributed	
data:	Gaussian	with	zero	mean	and	unit	variance.
In	practice	we	often	ignore	the	shape	of	the	distribution	and	just	transform	the	
data	 to	 center	 it	 by	 removing	 the	 mean	 value	 of	 each	 feature,	 then	 scale	 it	 by	
dividing	non-constant	features	by	their	standard	deviation.
For	 instance,	 many	 elements	 used	 in	 the	 objective	 function	 of	 a	 learning	
algorithm	 (such	as	 the	RBF	kernel	of	Support	Vector	Machines	or	 the	l1	and	l2	
regularizes of	linear	models)	assume	 that	all	 features	are	centered	around	zero	
and	have	variance	in	the	same	order.	If	a	feature	has	a	variance	that	is	orders	of	
magnitude	 larger	 those others,	 it	 might	 dominate	 the	 objective	 function	 and	
make	 the	 estimator	 unable	 to	 learn	 from	 other	 features	 correctly	 as	 expected.

In [18]:
from sklearn import preprocessing

1- Create	the	following matrix	X2:
1, -1, 2,
2, 0, 0,
0, 1, -1

In [19]:
X=[[1,-1,2],[2,0,0], [0,1,-1]]

2-			Print	the	matrix	and	compute	the	mean	of	the	variables.


In [20]:
print(X)
M = np.mean(X)
print("The mean of the variables is: {:.2f}".format(M))

[[1, -1, 2], [2, 0, 0], [0, 1, -1]]
The mean of the variables is: 0.44


D. Data visualization 

1- Import	the	Iris	dataset	using	:	iris	=	datasets.load_iris()
This	 data	 sets	 consists	 of	 3	 different	 types	 of	 irises’	 (Setosa,	 Versicolour,	 and	
Virginica)	 petal	 and	 sepal	 length,	 stored	 in	 a	 150x4	 numpy.ndarray

The	 rows being	 the	 samples	 and	 the	 columns	 being:	 Sepal	 Length,	 Sepal	 Width,	 Petal	
Length	and	Petal	Width. More	information about	this	dataset	can	be	found	here:	
https://archive.ics.uci.edu/ml/datasets/iris
The	 variable	 iris is	 an	 object	 in	 Phyton	 which	 contains	 the	 matrix	 of	 data	
(iris.data),	 the	 corresponding	 label	 (target),	 the	 names of	 the	 variables	
(feature_names)	and	the	name	of	classes	(target_names).

In [21]:
iris	=	datasets.load_iris()

2- Plot	 the	 data	 points	 into	 2D	 dimension	 with	 all	 the	 possible	 combination	
between	 variables	 and	 use	 the	label	 for	 the	 color points.	 Vizually,	which	is	 the	
better	combination	of	variables? Justify	the	answer.

3- Compute	 the	 correlations	 between	 each	 pair	 of	 variables	 by	 using	 the	
corrcoef function	 of	 numpy package.	 Can	 you	 validate	 the	 answer	 of	 the	
question	C.2	by	using	the	obtained	correlations? Justify	your	response.

4- Subplots	in	matplotlib
Test	&	Analyze	the	following	code	:

In [23]:
import matplotlib.pyplot as plt
import chart_studio.plotly as py
from plotly.offline import iplot
import plotly.tools as tls

fig = plt.figure()
ax1 = fig.add_subplot(221)
ax1.plot([1,2,3,4,5], [10,5,10,5,10], 'r-')
ax2 = fig.add_subplot(222) 
ax2.plot([1,2,3,4], [1,4,9,16], 'k-')
ax3 = fig.add_subplot(223) 
ax3.plot([1,2,3,4], [1,10,100,1000], 'b-')
ax4 = fig.add_subplot(224) 
ax4.plot([1,2,3,4], [0,0,1,1], 'g-')
plt.tight_layout() 
fig = plt.gcf()
plotly_fig = tls.mpl_to_plotly( fig )
plotly_fig['layout']['title'] = 'Simple Subplot Example Title'
plotly_fig['layout']['margin'].update({'t':40})
iplot(plotly_fig)